# Form implementation generated from reading ui file 'view/Principal.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1291, 760)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_principal = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_principal.setStyleSheet("")
        self.frame_principal.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_principal.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_principal.setObjectName("frame_principal")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_principal)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_principa_superior = QtWidgets.QFrame(parent=self.frame_principal)
        self.frame_principa_superior.setStyleSheet("")
        self.frame_principa_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_principa_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_principa_superior.setObjectName("frame_principa_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_principa_superior)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_menu = QtWidgets.QFrame(parent=self.frame_principa_superior)
        self.frame_menu.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(315, 16777215))
        self.frame_menu.setStyleSheet("QPushButton {\n"
"    background-color: #1b2845;\n"
"    color:white;\n"
"    font-size: 20px;\n"
"    border-radius:3px;\n"
"    height: 40px;\n"
"    font: 87 12pt \"Helvetica LT Std Cond Blk\";\n"
"}\n"
"QFrame {\n"
"background-color: #1b2845;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #274060;\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_main_page = QtWidgets.QPushButton(parent=self.frame_menu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("view\\../images/casa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_main_page.setIcon(icon)
        self.btn_main_page.setIconSize(QtCore.QSize(30, 30))
        self.btn_main_page.setObjectName("btn_main_page")
        self.verticalLayout_2.addWidget(self.btn_main_page)
        self.btn_select_folder = QtWidgets.QPushButton(parent=self.frame_menu)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("view\\../images/carpeta-de-seleccion-de-musica.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_select_folder.setIcon(icon1)
        self.btn_select_folder.setIconSize(QtCore.QSize(30, 30))
        self.btn_select_folder.setObjectName("btn_select_folder")
        self.verticalLayout_2.addWidget(self.btn_select_folder)
        self.btn_music_library = QtWidgets.QPushButton(parent=self.frame_menu)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("view\\../images/biblioteca-musica.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_music_library.setIcon(icon2)
        self.btn_music_library.setIconSize(QtCore.QSize(30, 30))
        self.btn_music_library.setObjectName("btn_music_library")
        self.verticalLayout_2.addWidget(self.btn_music_library)
        self.btn_queue = QtWidgets.QPushButton(parent=self.frame_menu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("view\\../images/cola-reproduccion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_queue.setIcon(icon3)
        self.btn_queue.setIconSize(QtCore.QSize(30, 30))
        self.btn_queue.setObjectName("btn_queue")
        self.verticalLayout_2.addWidget(self.btn_queue)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_menu)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("view\\../images/lista-reproduccion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.frame_menu)
        self.frame_main = QtWidgets.QFrame(parent=self.frame_principa_superior)
        self.frame_main.setStyleSheet("background-color:#274060;")
        self.frame_main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_main.setObjectName("frame_main")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_main)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stk_main = QtWidgets.QStackedWidget(parent=self.frame_main)
        self.stk_main.setObjectName("stk_main")
        self.pg_main = QtWidgets.QWidget()
        self.pg_main.setObjectName("pg_main")
        self.stk_main.addWidget(self.pg_main)
        self.pg_music_library = QtWidgets.QWidget()
        self.pg_music_library.setObjectName("pg_music_library")
        self.stk_main.addWidget(self.pg_music_library)
        self.pg_queue = QtWidgets.QWidget()
        self.pg_queue.setObjectName("pg_queue")
        self.stk_main.addWidget(self.pg_queue)
        self.horizontalLayout_3.addWidget(self.stk_main)
        self.horizontalLayout_2.addWidget(self.frame_main)
        self.verticalLayout.addWidget(self.frame_principa_superior)
        self.frame_reproductor = QtWidgets.QFrame(parent=self.frame_principal)
        self.frame_reproductor.setMinimumSize(QtCore.QSize(0, 215))
        self.frame_reproductor.setMaximumSize(QtCore.QSize(16777215, 215))
        self.frame_reproductor.setStyleSheet("background-color: #274060;")
        self.frame_reproductor.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_reproductor.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_reproductor.setLineWidth(5)
        self.frame_reproductor.setObjectName("frame_reproductor")
        self.verticalLayout.addWidget(self.frame_reproductor)
        self.horizontalLayout.addWidget(self.frame_principal)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1291, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_main_page.setText(_translate("MainWindow", "Página principal"))
        self.btn_select_folder.setText(_translate("MainWindow", "Seleccionar carpetas origen"))
        self.btn_music_library.setText(_translate("MainWindow", "Biblioteca de música"))
        self.btn_queue.setText(_translate("MainWindow", "Cola de reproducción"))
        self.pushButton.setText(_translate("MainWindow", "Listas de reproducción"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
